[theme]
# Primary color for buttons, links, etc. (e.g., Pink for Breast Cancer Awareness)
primaryColor="#0a5a16ff" 

# Background color of the main content area
backgroundColor="#084b58ff" 

# Background color of the sidebar and secondary elements
secondaryBackgroundColor="#b0255fff" 

# Color for text
textColor="#ececf0ff" 

# Font family
font="sans serif"